#
#JDBC properties - connecting to my database
#
#spring.datasource.url=jdbc:mysql://localhost:3306/video_directory
#spring.datasource.username=root
#spring.datasource.password=localpassword

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video_directory
    username: root
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail.smtp.ssl.trust: "*"
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000